### ISSUE TITLE
Error fiji.munki 

### ISSUE THREAD

**Issue by Peter-Erik** [autopkg/vmiller-recipes#16]
Hi fiji.munki gives an error:

The following recipes failed:
    fiji.munki
        Error in com.github.vmiller.munki.Fiji: Processor: URLTextSearcher: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'https://imagej.nih.gov/ij/notes.html']' returned non-zero exit status 60.

**Comment by vmiller** [comment]
Thanks for the report.  I saw this too, hopefully I can find some time today to look into it.

**Comment by vmiller** [comment]
Ahh, looks like the certificate has expired for https://imagej.nih.gov

Not much we can do about that on our end, hopefully they resolve this issue soon.

**Comment by Peter-Erik** [comment]
@vmiller thanks for your time

**Comment by vmiller** [comment]
This appears to be resolved now.
