### ISSUE TITLE
PowerShell has forked with a separate M1 and x86 version.

### ISSUE THREAD

**Issue by JoblessLoser** [autopkg/vmiller-recipes#18]
Hi, 

Feel a bit cheeky bring this up especially as I really need to start learning how to engineering these kind of things myself but.
The last update but one update that came through was an M1 processor only release and one that come through this morning was an x86 version.

-I think- As they both have the same version number -I think- The M1 version was successfully added to Munki (although I had to suppress it as it won't run on x86 computers) and the x86 version was not added.

if it's of any help going forward I have had success with the following M1 detection / Rosseta 2 installation script 
```
#!/bin/bash

if [[ $(uname -p) == 'arm' ]]; then
	if [[ "`pkgutil --pkgs-plist | grep 'com.apple.pkg.RosettaUpdateAuto' | wc -l | sed 's/ //g'`" == "0" ]]
	then 
		echo 'rosetta is not installed'
        sudo softwareupdate --install-rosetta --agree-to-license
	else
		echo 'rosetta is already installed'
	fi
fi
```

**Comment by vmiller** [comment]
As of this pull request https://github.com/autopkg/vmiller-recipes/pull/17 which was merged yesterday, the PowerShell recipe now supports specifying the desired architecture to be downloaded.  

The input key is ARCH with acceptable values being 'arm64' or 'x64'   So you can add this to your override and specify which architecture you want.
