### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/vmiller-recipes#25]
Hi, @vmiller 

Just raising an issue with the Tracker download recipe, seems the vendors has messed up the download URL.

Rather than downloading the DMG the [download URL](https://physlets.org/tracker/installers/download.php?file=Tracker-6.0.10-osx-installer.dmg) displays this:

```
<br />
<b>Warning</b>:  Undefined array key 1 in <b>/home/physlets/public_html/tracker/installers/download.php</b> on line <b>44</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/physlets/public_html/tracker/installers/download.php:44) in <b>/home/physlets/public_html/tracker/installers/download.php</b> on line <b>92</b><br />
```

**Comment by vmiller** [comment]
I looked at this earlier this morning and saw the dev's website was throwing an error.

Thanks for taking the time to open an issue.  Should be helpful to others who are seeing this recipe error out.

**Comment by vmiller** [comment]
It looks like the vendor's website issues have been resolved.
